# Generated by Django 3.2.6 on 2021-08-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0002_student1_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='user',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='relations_app.user1'),
        ),
    ]
