# Generated by Django 3.2.6 on 2021-08-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0005_manager_student2_user2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
    ]
