# Generated by Django 3.2.6 on 2021-08-05 06:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0006_alter_manager_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
    ]
