# Generated by Django 3.2.6 on 2021-08-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_inher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mul_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ano_table',
            fields=[
                ('mul_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_inher_app.mul_info')),
                ('salary', models.IntegerField()),
            ],
            bases=('model_inher_app.mul_info',),
        ),
    ]
