# Generated by Django 3.2.5 on 2021-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
