# Generated by Django 3.2.5 on 2021-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_alter_studentmodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='blood_group',
            field=models.CharField(choices=[('1', 'O'), ('2', 'A')], default='1', max_length=20, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=20),
        ),
    ]
