# Generated by Django 3.2.5 on 2021-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_studentmodel_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='blood_group',
            field=models.CharField(max_length=20, verbose_name='Blood Group'),
        ),
    ]
