# Generated by Django 3.2.5 on 2021-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abid', models.IntegerField()),
                ('abname', models.CharField(max_length=70)),
                ('abemail', models.EmailField(max_length=70)),
                ('abres', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indid', models.IntegerField()),
                ('indname', models.CharField(max_length=70)),
                ('indemail', models.EmailField(max_length=70)),
                ('indres', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.IntegerField()),
                ('stdname', models.CharField(max_length=70)),
                ('stdemail', models.EmailField(max_length=70)),
                ('stdres', models.CharField(max_length=70)),
            ],
        ),
    ]
