# Generated by Django 3.2.5 on 2021-07-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stdimg',
            field=models.ImageField(null=True, upload_to="url('/static/images)"),
        ),
    ]
